//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KapGel.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adress
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string cityName { get; set; }
        public string districtName { get; set; }
        public string neighborhoodName { get; set; }
        public string adress1 { get; set; }
    }
}
