//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KapGel.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KapGelEntities : DbContext
    {
        public KapGelEntities()
            : base("name=KapGelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adress> Adress { get; set; }
        public virtual DbSet<Brands> Brands { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Discounts> Discounts { get; set; }
        public virtual DbSet<Donation> Donation { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<MarketComment> MarketComment { get; set; }
        public virtual DbSet<Markets> Markets { get; set; }
        public virtual DbSet<MarketVote> MarketVote { get; set; }
        public virtual DbSet<Menus> Menus { get; set; }
        public virtual DbSet<MyBasket> MyBasket { get; set; }
        public virtual DbSet<Pages> Pages { get; set; }
        public virtual DbSet<ProductComment> ProductComment { get; set; }
        public virtual DbSet<productPicture> productPicture { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<ProductsInBasket> ProductsInBasket { get; set; }
        public virtual DbSet<ProductVote> ProductVote { get; set; }
        public virtual DbSet<Promotion> Promotion { get; set; }
        public virtual DbSet<PromotionProduct> PromotionProduct { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Token> Token { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<ForgotPassword> ForgotPassword { get; set; }
    }
}
