//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KapGel.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Markets
    {
        public int Id { get; set; }
        public string marketName { get; set; }
        public string phoneNumber { get; set; }
        public Nullable<System.DateTime> recordDate { get; set; }
        public Nullable<int> userId { get; set; }
        public string video { get; set; }
        public string marketPhoto { get; set; }
    }
}
