//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KapGel.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion
    {
        public int Id { get; set; }
        public Nullable<int> marketId { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
    }
}
