//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KapGel.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int id { get; set; }
        public string NameSurname { get; set; }
        public string eMail { get; set; }
        public string password { get; set; }
        public string phoneNumber { get; set; }
        public Nullable<byte> authority { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<System.DateTime> recordDate { get; set; }
    }
}
